apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.airflow.name }}-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: {{ .Values.airflow.name }}-pvc
    namespace: {{ .Release.Namespace }}
  hostPath:
    path: "/opt/airflow/"
